name: CI

on:
  push:
    branches: 'master'
  pull_request:
    branches: '*'
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install node
      uses: actions/setup-node@v1
      with:
       node-version: '12.x'
    - name: Install Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
        architecture: 'x64'

    - name: Setup pip cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: pip-3.7-${{ hashFiles('package.json') }}
        restore-keys: |
          pip-3.7-
          pip-

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"
    - name: Setup yarn cache
      uses: actions/cache@v2
      id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          yarn-

    - name: Install dependencies
      run: |
        python -m pip install jupyterlab~=3.0 cookiecutter jupyter_packaging~=0.9 check-manifest build

    - name: Create pure frontend extension
      run: |
        set -eux
        cookiecutter . --no-input
        pushd myextension
        jlpm install && jlpm run eslint:check
        pip install -e .
        jupyter labextension develop . --overwrite
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "myextension.*OK"
        python -m jupyterlab.browser_check

        jupyter labextension uninstall myextension
        pip uninstall -y myextension jupyterlab

        git init && git add .
        check-manifest -v

        popd
        rm -rf myextension

    - name: Create server extension pip install
      run: |
        set -eux
        # Trick to use custom parameters
        python -c "from cookiecutter.main import cookiecutter; import json; f = open('cookiecutter_with_server.json'); cookiecutter('.', extra_context=json.load(f), no_input=True); f.close()"
        pip install ./myextension
        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "myextension.*OK"
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "my_lab_extension.*OK"
        python -m jupyterlab.browser_check

        pip uninstall -y myextension jupyterlab
        rm -rf myextension

    - name: Create server extension pip develop
      run: |
        set -eux
        # Trick to use custom parameters
        python -c "from cookiecutter.main import cookiecutter; import json; f = open('cookiecutter_with_server.json'); cookiecutter('.', extra_context=json.load(f), no_input=True); f.close()"
        pushd myextension
        pip install -e .
        jupyter labextension develop . --overwrite
        jupyter server extension enable myextension
        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "myextension.*OK"
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "my_lab_extension.*OK"
        python -m jupyterlab.browser_check

        jupyter labextension develop . --overwrite
        jupyter labextension build .

        jupyter labextension uninstall my_lab_extension
        pip uninstall -y myextension jupyterlab
        popd
        rm -rf myextension

    - name: Install server extension from a tarball
      run: |
        set -eux
        # Trick to use custom parameters
        python -c "from cookiecutter.main import cookiecutter; import json; f = open('cookiecutter_with_server.json'); cookiecutter('.', extra_context=json.load(f), no_input=True); f.close()"
        pushd myextension
        pip install --pre jupyter_packaging jupyterlab
        jupyter lab clean --all
        python -m build --sdist
        pip install dist/*.tar.gz
        jupyter labextension list
        jupyter labextension list 2>&1 | grep -ie "my_lab_extension.*OK"
        jupyter server extension list
        jupyter server extension list 2>&1 | grep -ie "myextension.*OK"

        jupyter lab build --dev-build --no-minimize
        python -m jupyterlab.browser_check

        pip uninstall -y myextension jupyterlab
        popd
        rm -rf myextension
